# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3249d468bb863eb776db72d9fc122e3468e4f17c94dcf48d7d8d2dc592938c5d65934d769232755d8dfc59e6d7de434347028f06247ce3b192e5ccc0db8f1f63

test:
  secret_key_base: ff4177b408a98be3fa05398077832f670628adee73fa1b616f4a5271596b1395e41a08ed83e126a0a1ca7c474ea67b398f4270c52d16c9a2acf6d7e285027114

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
